import type { Category, Product, SiteSettings } from "@/lib/types";

export const demoCategories: Category[] = [
  {
    id: "wax-sachets",
    name: "Wax Sachets",
    slug: "wax-sachets",
    description: "Handcrafted wax sachets for wardrobes, drawers, cars, bags, and closed spaces.",
    parent_id: null,
    sort_order: 1,
  },
  {
    id: "candles",
    name: "Candles",
    slug: "candles",
    description: "Hand-poured candles crafted for a slow, clean, aesthetic burn.",
    parent_id: null,
    sort_order: 2,
  },
];

export const demoSettings: SiteSettings = {
  brand_name: "Moments by Isha",
  whatsapp_number: "+91 76665 79729",
  whatsapp_message_template: "Hi, I want to order {{product_name}} from Moments by Isha.",
  contact_email: "hello@momentsbyisha.com",
  instagram_url: "https://instagram.com/shah_artisans.aroma",
  home_hero_image_url: "",
  home_story_image_url: "",
  about_hero_image_url: "",
  about_founder_image_url: "",
};

const images = [
  "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1612196808214-b40e9fb9f537?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1595425964077-c9703cf48b6f?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1602874801007-bd458bb1b8b6?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1608755727748-dfa2e44f2558?auto=format&fit=crop&w=1200&q=85",
];

export const demoProducts: Product[] = [
  {
    id: "simple-sachet",
    name: "Simple Sachet",
    slug: "simple-sachet",
    description: "Simple wax sachet with artificial embedded flowers. Available in any fragrance or shape.",
    price: "₹200",
    category_id: "wax-sachets",
    image_url: images[0],
    gallery_images: [],
    is_featured: true,
    is_visible: true,
    sort_order: 1,
    categories: demoCategories[0],
  },
  {
    id: "colour-wax-sachet-embedded-flowers",
    name: "Colour Wax Sachet with Embedded Flowers",
    slug: "colour-wax-sachet-embedded-flowers",
    description: "Colour wax sachet with artificial embedded flowers. Available in any fragrance, shape, or colour.",
    price: "₹220",
    category_id: "wax-sachets",
    image_url: images[1],
    gallery_images: [],
    is_featured: true,
    is_visible: true,
    sort_order: 2,
    categories: demoCategories[0],
  },
  {
    id: "colour-wax-sachet-wax-embedded-design",
    name: "Colour Wax Sachet with Wax Embedded Design",
    slug: "colour-wax-sachet-wax-embedded-design",
    description: "Colour wax sachet with wax embedded design. Available in any fragrance, shape, or colour.",
    price: "₹240",
    category_id: "wax-sachets",
    image_url: images[2],
    gallery_images: [],
    is_featured: false,
    is_visible: true,
    sort_order: 3,
    categories: demoCategories[0],
  },
  {
    id: "premium-colour-wax-sachet",
    name: "Premium Colour Wax Sachet",
    slug: "premium-colour-wax-sachet",
    description: "Premium colour wax sachet with wax embedded design. Available in any fragrance, shape, or colour.",
    price: "₹260",
    category_id: "wax-sachets",
    image_url: images[3],
    gallery_images: [],
    is_featured: false,
    is_visible: true,
    sort_order: 4,
    categories: demoCategories[0],
  },
  {
    id: "sunshine-bouquet",
    name: "Sunshine Bouquet",
    slug: "sunshine-bouquet",
    description: "Handcrafted mini sunflower bouquet, perfect for small and meaningful gifting. Available in any fragrance.",
    price: "₹199",
    category_id: "candles",
    image_url: images[4],
    gallery_images: [],
    is_featured: true,
    is_visible: true,
    sort_order: 5,
    categories: demoCategories[1],
  },
  {
    id: "brewed-bliss",
    name: "Brewed Bliss",
    slug: "brewed-bliss",
    description: "Iced coffee themed candle, 200 ml. Fragrance: Coffee Latte. Burn time: 18-20 hrs.",
    price: "₹799",
    category_id: "candles",
    image_url: images[5],
    gallery_images: [],
    is_featured: true,
    is_visible: true,
    sort_order: 6,
    categories: demoCategories[1],
  },
  {
    id: "sunkissed-shore",
    name: "Sunkissed Shore",
    slug: "sunkissed-shore",
    description: "Beach themed candle, 200 ml. Fragrance: Sea Breeze. Burn time: 16-18 hrs.",
    price: "₹799",
    category_id: "candles",
    image_url: images[0],
    gallery_images: [],
    is_featured: true,
    is_visible: true,
    sort_order: 7,
    categories: demoCategories[1],
  },
  {
    id: "lavender-bloom",
    name: "Lavender Bloom",
    slug: "lavender-bloom",
    description: "Lavender-inspired candle for self-care, evenings, gifting, and a luxurious decor accent.",
    price: "₹799",
    category_id: "candles",
    image_url: images[1],
    gallery_images: [],
    is_featured: false,
    is_visible: true,
    sort_order: 8,
    categories: demoCategories[1],
  },
  {
    id: "the-arch-aura",
    name: "The Arch Aura",
    slug: "the-arch-aura",
    description: "Sculptural candle with 20-24 hr burn time. Available in any fragrance.",
    price: "₹399",
    category_id: "candles",
    image_url: images[2],
    gallery_images: [],
    is_featured: false,
    is_visible: true,
    sort_order: 9,
    categories: demoCategories[1],
  },
];
